//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AraçTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AraçTablosu()
        {
            this.Sirket_Arac = new HashSet<Sirket_Arac>();
        }
    
        public int Aracid { get; set; }
        public string Plaka { get; set; }
        public Nullable<int> AracCikisKM { get; set; }
        public Nullable<int> AracDönüsKM { get; set; }
        public Nullable<int> Durumu { get; set; }
        public Nullable<int> TahsisEdilen { get; set; }
        public string Model { get; set; }
        public Nullable<int> KullanilanBolge { get; set; }
    
        public virtual BölgelerTablosu BölgelerTablosu { get; set; }
        public virtual KullaniciTablosu KullaniciTablosu { get; set; }
        public virtual KullaniciTablosu KullaniciTablosu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sirket_Arac> Sirket_Arac { get; set; }
    }
}
