//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BölgelerTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BölgelerTablosu()
        {
            this.AraçTablosu = new HashSet<AraçTablosu>();
            this.Kargo = new HashSet<Kargo>();
            this.Kargo1 = new HashSet<Kargo>();
            this.KullaniciTablosu = new HashSet<KullaniciTablosu>();
            this.Sirket_Arac = new HashSet<Sirket_Arac>();
            this.Ziyaretci = new HashSet<Ziyaretci>();
            this.Ithalat_Ihracat_Arac = new HashSet<Ithalat_Ihracat_Arac>();
        }
    
        public int Bölge_id { get; set; }
        public Nullable<int> Sehir { get; set; }
        public string Adres { get; set; }
        public string Bölge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AraçTablosu> AraçTablosu { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kargo> Kargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kargo> Kargo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciTablosu> KullaniciTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sirket_Arac> Sirket_Arac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ziyaretci> Ziyaretci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ithalat_Ihracat_Arac> Ithalat_Ihracat_Arac { get; set; }
    }
}
