//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DgsForm
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UnitOfDepartment { get; set; }
        public string CodeOfProject { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<short> MissionId { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
    
        public virtual KullaniciTablosu KullaniciTablosu { get; set; }
        public virtual Mission Mission { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
