//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ithalat_Ihracat_Arac
    {
        public int ihracataracid { get; set; }
        public string nakliyetur { get; set; }
        public string tasiyicifirmaad { get; set; }
        public string tasiyiciplaka { get; set; }
        public string soforadsoyad { get; set; }
        public string sofortc { get; set; }
        public string sofortel { get; set; }
        public string sevkyeri { get; set; }
        public string irsaliyeno { get; set; }
        public string muhurno { get; set; }
        public string koliadet { get; set; }
        public Nullable<System.DateTime> giristarih { get; set; }
        public Nullable<System.DateTime> cikistarih { get; set; }
        public string irsaliyetarih4 { get; set; }
        public Nullable<System.DateTime> irsaliyetarih { get; set; }
        public Nullable<int> kullaniciid { get; set; }
        public Nullable<int> bolgeid { get; set; }
        public string ikincikullanici { get; set; }
    
        public virtual BölgelerTablosu BölgelerTablosu { get; set; }
        public virtual KullaniciTablosu KullaniciTablosu { get; set; }
    }
}
