
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;

    public partial class KargoHareketleri
    {
        public int Id { get; set; }
        public Nullable<int> KargoNo { get; set; }
        public Nullable<int> TeslimAlanBolgeId { get; set; }
        public Nullable<int> TeslimAlanDepartmanId { get; set; }
        public Nullable<int> TeslimAlanPersonelId { get; set; }
        public Nullable<byte> GonderimTuruId { get; set; }
        public string AracPlakaNo { get; set; }
        public string KargoTakipNo { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Durum { get; set; }
        public string TeslimAlanPersonelAdSoyad { get; set; }

        public virtual GonderimTuru GonderimTuru { get; set; }
        public virtual Kargo Kargo { get; set; }
        public virtual BölgelerTablosu BölgelerTablosu { get; set; }
        public virtual DepartmanlarTablosu DepartmanlarTablosu { get; set; }
        public virtual KullaniciTablosu KullaniciTablosu { get; set; }
    }
}
