//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KullaniciTablosu()
        {
            this.AraçTablosu = new HashSet<AraçTablosu>();
            this.AraçTablosu1 = new HashSet<AraçTablosu>();
            this.DgsForm = new HashSet<DgsForm>();
            this.RolYetkiAtama = new HashSet<RolYetkiAtama>();
            this.Sirket_Arac = new HashSet<Sirket_Arac>();
            this.Ziyaretci = new HashSet<Ziyaretci>();
            this.Ithalat_Ihracat_Arac = new HashSet<Ithalat_Ihracat_Arac>();
        }
    
        public int Kullanici_id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TC { get; set; }
        public string SicilNo { get; set; }
        public Nullable<int> BölgeID { get; set; }
        public Nullable<int> DepatmanID { get; set; }
        public string TelefonNo { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> RolTipi { get; set; }
        public Nullable<int> YetkiTipi { get; set; }
        public string MaliyetMNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AraçTablosu> AraçTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AraçTablosu> AraçTablosu1 { get; set; }
        public virtual BölgelerTablosu BölgelerTablosu { get; set; }
        public virtual DepartmanlarTablosu DepartmanlarTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DgsForm> DgsForm { get; set; }
        public virtual Roller Roller { get; set; }
        public virtual Yetki Yetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolYetkiAtama> RolYetkiAtama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sirket_Arac> Sirket_Arac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ziyaretci> Ziyaretci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ithalat_Ihracat_Arac> Ithalat_Ihracat_Arac { get; set; }
    }
}
