//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTProje.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TYHTALEPEntities : DbContext
    {
        public TYHTALEPEntities()
            : base("name=TYHTALEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AraçTablosu> AraçTablosu { get; set; }
        public virtual DbSet<BölgelerTablosu> BölgelerTablosu { get; set; }
        public virtual DbSet<DepartmanlarTablosu> DepartmanlarTablosu { get; set; }
        public virtual DbSet<DgsForm> DgsForm { get; set; }
        public virtual DbSet<FollowPackages> FollowPackages { get; set; }
        public virtual DbSet<GonderimTuru> GonderimTuru { get; set; }
        public virtual DbSet<Kargo> Kargo { get; set; }
        public virtual DbSet<KargoHareketleri> KargoHareketleri { get; set; }
        public virtual DbSet<KullaniciTablosu> KullaniciTablosu { get; set; }
        public virtual DbSet<Mission> Mission { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<RolYetkiAtama> RolYetkiAtama { get; set; }
        public virtual DbSet<Sehirler> Sehirler { get; set; }
        public virtual DbSet<SeyahatRezTablosu> SeyahatRezTablosu { get; set; }
        public virtual DbSet<SeyahatTipleriTablosu> SeyahatTipleriTablosu { get; set; }
        public virtual DbSet<Sirket_Arac> Sirket_Arac { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
        public virtual DbSet<Yolcu> Yolcu { get; set; }
        public virtual DbSet<Ziyaretci> Ziyaretci { get; set; }
        public virtual DbSet<ArgeUnit> ArgeUnit { get; set; }
        public virtual DbSet<Ithalat_Ihracat_Arac> Ithalat_Ihracat_Arac { get; set; }
    }
}
