//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolYetkiAtama
    {
        public int Atama_Id { get; set; }
        public Nullable<int> Kullanici_Id { get; set; }
        public Nullable<int> Rol_Id { get; set; }
        public Nullable<int> Yetki_Id { get; set; }
    
        public virtual KullaniciTablosu KullaniciTablosu { get; set; }
        public virtual Roller Roller { get; set; }
        public virtual Yetki Yetki { get; set; }
    }
}
