//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeyahatTipleriTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeyahatTipleriTablosu()
        {
            this.SeyahatRezTablosu = new HashSet<SeyahatRezTablosu>();
        }
    
        public int Seyahat_id { get; set; }
        public string SeyahatT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeyahatRezTablosu> SeyahatRezTablosu { get; set; }
    }
}
