//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yolcu
    {
        public int yolcuid { get; set; }
        public Nullable<int> ykullaniciid { get; set; }
        public string yolcuadsoyad { get; set; }
        public string yolcubirim { get; set; }
        public Nullable<int> gorevid { get; set; }
    
        public virtual Sirket_Arac Sirket_Arac { get; set; }
    }
}
