//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ziyaretci
    {
        public int ziyaretciid { get; set; }
        public string z_adsoyad { get; set; }
        public string ziyaretsebebi { get; set; }
        public string z_edilenadsoyad { get; set; }
        public string z_tcno { get; set; }
        public string kartno { get; set; }
        public string z_plaka { get; set; }
        public Nullable<System.DateTime> z_giristarih { get; set; }
        public Nullable<System.DateTime> z_cikistarih { get; set; }
        public Nullable<int> kullaniciid { get; set; }
        public Nullable<int> birimid { get; set; }
        public Nullable<int> bolgeid { get; set; }
        public string ikincikullanici { get; set; }
    
        public virtual BölgelerTablosu BölgelerTablosu { get; set; }
        public virtual DepartmanlarTablosu DepartmanlarTablosu { get; set; }
        public virtual KullaniciTablosu KullaniciTablosu { get; set; }
    }
}
